
### Create nginx basic pod
### kubectl create pod nginx --image=nginx --namespace=network-demo 

### Create busybox basic pod
### kubectl create pod busybox --image=busybox --namespace=network-demo --command -- sleep 3600

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress
  namespace: network-demo
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Ingress
  ingress:
  - []  # No ingress rules, effectively denying all ingress traffic